version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    networks:
      - app-tier
    ports:
      - '6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '6379'
    depends_on:
      - redis
    networks:
      - app-tier
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_SET=redis
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    networks:
      - app-tier

  app:
    container_name: app
    image: app:0.0.1-SNAPSHOT
    environment:
      SPRING_REDIS_SENTINEL_MASTER: redis
      SPRING_REDIS_SENTINEL_NODES: redis-sentinel:26379
      SPRING_REDIS_SENTINEL_PASSWORD: str0ng_passw0rd
      SPRING_REDIS_PASSWORD: str0ng_passw0rd
    networks:
      - app-tier
    depends_on:
      - redis-sentinel
    ports:
      - 8080:8080