version: "3"

networks:
  app-tier:
    driver: bridge

services:
  redis-master:
    container_name: redis-master
    image: redis:alpine
    command: redis-server --port 6379
    networks:
      - app-tier
    ports:
      - 6379:6379

  redis-replica-1:
    container_name: redis-replica-1
    image: redis:alpine
    command: redis-server --replicaof redis-master 6379 --port 6379
    networks:
      - app-tier
    ports:
      - 7001:6379

  redis-replica-2:
    container_name: redis-replica-2
    image: redis:alpine
    command: redis-server --replicaof redis-master 6379 --port 6379
    networks:
      - app-tier
    ports:
      - 7002:6379

  app:
    container_name: app
    image: app:0.0.1-SNAPSHOT
    environment:
      REDIS_MASTER: "redis-master:6379"
      REDIS_SLAVES: "redis-replica-1:7001, redis-replica-2:7002"
    networks:
      - app-tier
    ports:
      - 8080:8080